// Copyright (c) Bruno Sales <me@baliestri.dev>. Licensed under the MIT License.
// See the LICENSE file in the repository root for full license text.

using System.Diagnostics.CodeAnalysis;
using System.Security.Cryptography;

namespace OIDC.Infra.Common.Adapter.Utilities;

[ExcludeFromCodeCoverage]
internal static class RandomGeneratorUtility {
  /// <summary>
  ///   Generates a random byte array.
  /// </summary>
  /// <param name="size">The size of the byte array to be generated.</param>
  /// <returns>The generated byte array.</returns>
  public static byte[] GetRandomBytes(int size) {
    using var rng = RandomNumberGenerator.Create();
    var buffer = new byte[size];
    rng.GetBytes(buffer);

    return buffer;
  }
}
